package com.example.utocka


val imageResourceList = listOf(
    R.drawable.goose,
    R.drawable.duck,
    R.drawable.adventurer,
    R.drawable.assassin,
    R.drawable.astral,
    R.drawable.avenger,
    R.drawable.birdwatcher,
    R.drawable.canadian,
    R.drawable.cannibal,
    R.drawable.celebrity,
    R.drawable.cupid,
    R.drawable.demolitionist,
    R.drawable.detective,
    R.drawable.dodo,
    R.drawable.duelingdodos,
    R.drawable.esper,
    R.drawable.falcon,
    R.drawable.gravy,
    R.drawable.hitman,
    R.drawable.invisibility,
    R.drawable.lover,
    R.drawable.medium,
    R.drawable.mimic,
    R.drawable.morphling,
    R.drawable.mortician,
    R.drawable.party,
    R.drawable.pelican,
    R.drawable.pigeon,
    R.drawable.preacher,
    R.drawable.professional,
    R.drawable.serialkiller,
    R.drawable.sheriff,
    R.drawable.silencer,
    R.drawable.spy,
    R.drawable.stalker,
    R.drawable.undertaker,
    R.drawable.vigilante
)